Repository Igalia/cog, pull requests merged in 2020-04, with the labels that each got.

#185 Keep a reference to the config GKeyFile on CogShell
  cog.c
  core/cog-shell.c
  core/cog-shell.h
Labels: enhancement

#200 cmake: Fix passing -DWAYLAND_PROTOCOLS= on command line
  cmake/FindWaylandProtocols.cmake
Labels: bug, merge:cog-0.6

#203 fdo: Avoid repeatedly setting opaque regions
  platform/cog-platform-fdo.c
Labels: enhancement, merge:cog-0.6
