Repository Igalia/cog, pull requests merged in 2021-03, with the labels that each got.

#266 core: Allow resolving base path in URI files handler
  core/cog-directory-files-handler.c
Labels: bug, merge:cog-0.8

#271 CI: Switch from Travis-CI to GitHub Actions
  .github/toolchain.sh
  .github/workflows/ci.yml
  .travis.yml
Labels: enhancement

#277 fdo: Fix include after #269
  platform/fdo/cog-platform-fdo.c
Labels: bug

#278 cmake: Make it easier to use uninstalled platform modules
  platform/drm/CMakeLists.txt
  platform/fdo/CMakeLists.txt
Labels: bug, enhancement

#273 platform: Add basic headless platform plugin
  CMakeLists.txt
  platform/headless/CMakeLists.txt
  platform/headless/cog-platform-headless.c
Labels: enhancement

#251 Remove default about:blank load action in the View constructor
  core/cog-view.c
Labels: enhancement

#268 drm: support wpe_fdo_shm_exported_buffer exports
  platform/drm/cog-platform-drm.c
Labels: enhancement

#267 fdo: support wpe_fdo_shm_exported_buffer exports
  platform/fdo/cog-platform-fdo.c
Labels: enhancement

#281 drm: add necessary guards for SHM export handling
  platform/drm/cog-platform-drm.c
Labels: bug

#282 fdo: Use WAYLAND_VERSION_* instead of CMake check
  core/cog-config.h.in
  platform/fdo/CMakeLists.txt
  platform/fdo/cog-platform-fdo.c
Labels: bug

#286 CI: Publish docs on pushes to main branch
  .github/workflows/ci-native.yml
Labels: enhancement
