Repository Igalia/cog, pull requests merged in 2022-03, with the labels that each got.

#408 wl: Document supported environment variables
  docs/platform-wl.md
Labels: enhancement

#409 x11: Fix underlinking when --as-needed is used
  platform/x11/CMakeLists.txt
Labels: bug

#414 wl: Use wl_compositor v3 features if available
  platform/wayland/cog-platform-wl.c
Labels: bug, merge:cog-0.12

#415 wl: Fix request of wl_seat version and guard feature usage
  platform/wayland/cog-platform-wl.c
Labels: bug

#417 Fix WPE_FDO_CHECK_VERSION macro name and fdo buffer release function name.
  platform/wayland/cog-platform-wl.c
Labels: bug
