Repository Igalia/cog, pull requests merged in 2023-05, with the labels that each got.

#563 drm: ignore key event if no xkb context is available
  platform/drm/cog-platform-drm.c
Labels: bug

#565 launcher: Simplify by using global CogPlatform
  launcher/cog-launcher.c
Labels: enhancement

#568 headless: Move frame tick source to platform object
  platform/headless/cog-platform-headless.c
Labels: enhancement

#572 core: Move platform selection logic into the library
  core/cog-platform.c
  core/cog-platform.h
  launcher/cog-launcher.c
Labels: enhancement

#571 wl: fix blurry rendering in some compositors
  platform/wayland/cog-platform-wl.c
Labels: bug, enhancement, merge:cog-0.18

#570 core: Introduce a new CogView class
  core/cog-platform.h
  core/cog-shell.c
  core/cog-view.c
  core/cog-view.h
  core/cog.h
  core/meson.build
  launcher/cog-launcher.c
Labels: enhancement

#574 core: Move key binding handling into CogView
  core/cog-view.c
  core/cog-view.h
  docs/platform-wl.md
  platform/drm/cog-platform-drm.c
  platform/gtk4/cog-platform-gtk4.c
  platform/wayland/cog-platform-wl.c
  platform/x11/cog-platform-x11.c
Labels: enhancement

#576 launcher: Add CLI flag to disable built-in key bindings
  data/cog.1
  launcher/cog-launcher.c
Labels: enhancement
