Repository Igalia/cog, pull requests merged in 2023-11, with the labels that each got.

#635 wl: Refactor popup_data as CogWlPopup
  platform/wayland/cog-platform-wl.c
  platform/wayland/cog-platform-wl.h
  platform/wayland/cog-utils-wl.c
  platform/wayland/cog-utils-wl.h
  platform/wayland/cog-view-wl.c
Labels: enhancement

#650 wl: Fix Meson configure error when Cog is build only for wayland
  platform/meson.build
Labels: bug, merge:cog-0.18

#653 Add missing cog-export.h header in the cogcore_headers
  core/meson.build
Labels: bug

#651 Fix build with using glib<2.63.1
  core/cog-platform.c
Labels: enhancement

#656 core: Add some convenience to the module loader
  core/cog-modules.c
  examples/viewport.c
  launcher/cog.c
Labels: enhancement

#657 wl: Un-hardcode the fixed amount of outputs
  platform/wayland/cog-platform-wl.c
  platform/wayland/cog-utils-wl.c
  platform/wayland/cog-utils-wl.h
Labels: enhancement

#554 Fix touch limit raw region when rotate screen
  platform/drm/cog-platform-drm.c
Labels: bug

#660 drm: Update logical input area size on property changes
  platform/drm/cog-platform-drm.c
Labels: bug, enhancement, merge:cog-0.18

#661 wl: Fix unused variable display warning
  platform/wayland/cog-platform-wl.c
Labels: enhancement

#655 core: Remove cog_platform_configure() function
  core/cog-platform.c
  core/cog-platform.h
  core/cog-view.c
  docs/cog.toml.in
  docs/running.md
  examples/viewport.c
  launcher/cog-launcher.c
  launcher/cog.c
  platform/wayland/cog-platform-wl.c
  platform/wayland/cog-utils-wl.c
  platform/wayland/cog-view-wl.c
Labels: enhancement

#659 core: Make cog_modules_add_directory() honor COG_MODULEDIR
  core/cog-modules.c
  core/cog-platform.c
Labels: enhancement

#658 core: Allow passing NULL as platform setup params
  core/cog-platform.c
  docs/running.md
  examples/viewport.c
  launcher/cog-launcher.c
Labels: enhancement

#665 wl: Attach Viewport to the surface
  platform/wayland/cog-platform-wl.c
  platform/wayland/cog-utils-wl.c
  platform/wayland/cog-utils-wl.h
  platform/wayland/cog-viewport-wl.c
Labels: enhancement

#674 core: Make the CogView.viewport property only readable
  core/cog-view.c
Labels: bug

#673 x11: Do not attempt to set an invalid cursor
  platform/x11/cog-platform-x11.c
Labels: bug

#669 wl: Check wl_surface before use it
  platform/wayland/cog-platform-wl.c
Labels: bug

#671 wl: Change IM context functions signature
  core/cog-platform.c
  core/cog-platform.h
  core/cog-viewport.c
  launcher/cog-launcher.c
  platform/wayland/cog-platform-wl.c
  platform/wayland/cog-utils-wl.c
  platform/wayland/cog-utils-wl.h
Labels: enhancement

#676 wl: Fix the COG_PLATFORM_WL_VIEW_FULLSCREEN not works
  platform/wayland/cog-viewport-wl.c
Labels: bug
